<?php
require __DIR__ . '/../inc/bootstrap.php';
$division = filter_var($_POST['division'], FILTER_SANITIZE_NUMBER_INT);
$teamid1 = filter_var($_POST['team1'], FILTER_SANITIZE_STRING);
$teamid2 = filter_var($_POST['team2'], FILTER_SANITIZE_STRING);
$score1 = filter_var($_POST['score1'], FILTER_SANITIZE_NUMBER_INT);
$score2 = filter_var($_POST['score2'], FILTER_SANITIZE_NUMBER_INT);
$season_id = 2;
$points1 = $score1 > $score2 ? 2 : 0;
$points2 = 2 - $points1;
$sth = $db->prepare("insert into matches values (NULL, :season_id, :division, :teamid1, :teamid2, :score1, :score2, :points1, :points2)");
$sth->bindValue(':season_id', $season_id, PDO::PARAM_INT);
$sth->bindValue(':division', $division, PDO::PARAM_INT);
$sth->bindValue(':teamid1', $teamid1, PDO::PARAM_INT);
$sth->bindValue(':teamid2', $teamid2, PDO::PARAM_INT);
$sth->bindValue(':score1', $score1, PDO::PARAM_INT);
$sth->bindValue(':score2', $score2, PDO::PARAM_INT);
$sth->bindValue(':points1', $points1, PDO::PARAM_INT);
$sth->bindValue(':points2', $points2, PDO::PARAM_INT);
$sth->execute();